[package]
name = "kademlia"
version = "0.1.0"
authors = ["tanyav2 <tanyav2@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
uint = "0.8.3"
rust-crypto = "0.2.36"
